### ISSUE TITLE
Getting $handle not found error 

### ISSUE THREAD

**Issue by brandonbryant12** [uptimesv/polynym#1]
Handcash 2.0 no longer supports the old api.  All handcash handles resolve to `handle@handcash.io`

A quick fix:

     //HandCash

    async function callHandCash(id) {

      id = id.toLowerCase();

      id = id.replace('$','');

      id = `${id}@handcash.io`;

      return axios.get('https://api.polynym.io/getAddress/' + id);
 
    }

you will also have to return `x.data.address` from `callHandCash(id) rather than `x.data.receivingAddress`

**Comment by deanmlittle** [comment]
Cheers dude. I've patched this on server, npm and github :)
